server:
    port: 8085

spring:
    application:
      name: notification

    datasource:
        url: jdbc:postgresql://postgres:5432/courseland-notification
        username: postgres_user
        password: password

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
              dialect: org.hibernate.dialect.PostgreSQL95Dialect
              show_sql: true
              format_sql: true
              ddl-auto: none
        generate-ddl: false

    zipkin:
      base-url: http://zipkin:9411

    rabbitmq:
        addresses: rabbitmq:5672

eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true

rabbitmq:
    exchanges:
        internal: internal.exchange
    queues:
        notification: notification.queue
    routing-keys:
        internal-notification: internal.notification.routing-key
